
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace MCSM {
    using System;
    using Terminal.Gui;
    
    
    public partial class InputDialog : Terminal.Gui.Dialog {
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.TextField textField;
        
        private Terminal.Gui.Button button2;
        
        private Terminal.Gui.Button button;
        
        private void InitializeComponent() {
            this.button = new Terminal.Gui.Button();
            this.button2 = new Terminal.Gui.Button();
            this.textField = new Terminal.Gui.TextField();
            this.label = new Terminal.Gui.Label();
            this.Width = 50;
            this.Height = 10;
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Modal = true;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = true;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Change Properties";
            this.label.Width = 15;
            this.label.Height = 1;
            this.label.X = Pos.Center();
            this.label.Y = 1;
            this.label.Visible = true;
            this.label.Data = "label";
            this.label.Text = "--Give a Value--";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label);
            this.textField.Width = Dim.Percent(75f);
            this.textField.Height = 1;
            this.textField.X = Pos.Center();
            this.textField.Y = 3;
            this.textField.Visible = true;
            this.textField.Secret = false;
            this.textField.Data = "textField";
            this.textField.Text = "";
            this.textField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textField);
            this.button2.Width = 10;
            this.button2.Height = 1;
            this.button2.X = 8;
            this.button2.Y = 6;
            this.button2.Visible = true;
            this.button2.Data = "button2";
            this.button2.Text = "OK";
            this.button2.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button2.IsDefault = false;
            this.AddButton(this.button2);
            this.button.Width = 6;
            this.button.Height = 1;
            this.button.X = 31;
            this.button.Y = 6;
            this.button.Visible = true;
            this.button.Data = "button";
            this.button.Text = "CANCEL";
            this.button.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button.IsDefault = false;
            this.AddButton(this.button);
        }
    }
}
