
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

using Terminal.Gui;

namespace MCSM {
    public partial class MainForm {
        private OpenDialog FileOpens;
        private SaveDialog FileSave;
        
        
        //服务器菜单
        private MenuItem Start;
        private MenuItem Stop;
        
        //环境菜单
        private MenuItem SetJava;
        private MenuItem SetServer;



        public MainForm() {
            InitMenuNTabs();
        }
        
    }

}
