
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

using System.Data.SqlTypes;
using Terminal.Gui;

namespace MCSM {
    public partial class MainForm {
        private OpenDialog FileOpens;
        private SaveDialog FileSave;

        public MainForm() {
            MainProc.DispStyle = new (){
                Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black),//正常
                HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black),//子视图聚焦
                Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.DarkGray),//激活但失焦，后者为输入区底色
                HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Gray),//选中
                Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black)//输入区域内部颜色，后者选中时底色
            };
            InitMenuNTabs();
        }

        public override bool ProcessHotKey (KeyEvent keyEvent)
		{
			if (base.ProcessHotKey (keyEvent)) {
				return true;
			}

			if (this.IsMdiChild && Application.Top.ProcessHotKey (keyEvent)) {
				return true;
			}
            if ((int)keyEvent.KeyValue + 2147483648 == (int)Key.a){
                tabView2.SetFocus();
                return true;
            }
            if ((int)keyEvent.KeyValue + 2147483648 == (int)Key.d){
                tabView.SetFocus();
                return true;
            }
			return false;
		}

    }

}
