
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

using System.Data.SqlTypes;
using Terminal.Gui;

namespace MCSM {
    public partial class MainForm {
        private OpenDialog FileOpens;
        private SaveDialog FileSave;
        
        
        //服务器菜单
        private MenuItem Start;
        private MenuItem Stop;
        
        //环境菜单
        private MenuItem SetJava;
        private MenuItem SetServer;



        public MainForm() {
            InitMenuNTabs();
        }

        public override bool ProcessHotKey (KeyEvent keyEvent)
		{
			if (base.ProcessHotKey (keyEvent)) {
				return true;
			}

			if (this.IsMdiChild && Application.Top.ProcessHotKey (keyEvent)) {
				return true;
			}
            if ((int)keyEvent.KeyValue + 2147483648 == (int)Key.a){
                tabView2.SetFocus();
                return true;
            }
            if ((int)keyEvent.KeyValue + 2147483648 == (int)Key.d){
                tabView.SetFocus();
                return true;
            }
			return false;
		}

    }

}
