
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace MCSM {
    using System;
    using Terminal.Gui;
    
    
    public partial class FileEditor : Terminal.Gui.View {
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.Button button;
        
        private Terminal.Gui.Button button2;
        
        private Terminal.Gui.TextView textView;
        
        private void InitializeComponent() {
            this.textView = new Terminal.Gui.TextView();
            this.button2 = new Terminal.Gui.Button();
            this.button = new Terminal.Gui.Button();
            this.label = new Terminal.Gui.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.label.Width = 34;
            this.label.Height = 1;
            this.label.X = 2;
            this.label.Y = 1;
            this.label.Visible = true;
            this.label.Data = "label";
            this.label.Text = "No File Opened";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label);
            this.button.Width = 7;
            this.button.Height = 2;
            this.button.X = 2;
            this.button.Y = 3;
            this.button.Visible = true;
            this.button.Data = "button";
            this.button.Text = "Open";
            this.button.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button.IsDefault = false;
            this.Add(this.button);
            this.button2.Width = 8;
            this.button2.Height = 1;
            this.button2.X = 11;
            this.button2.Y = 3;
            this.button2.Visible = true;
            this.button2.Data = "button2";
            this.button2.Text = "Save";
            this.button2.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button2.IsDefault = false;
            this.Add(this.button2);
            this.textView.Width = 51;
            this.textView.Height = 23;
            this.textView.X = 2;
            this.textView.Y = 5;
            this.textView.Visible = true;
            this.textView.AllowsTab = true;
            this.textView.AllowsReturn = true;
            this.textView.WordWrap = false;
            this.textView.Data = "textView";
            this.textView.Text = "Heya";
            this.textView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textView);
        }
    }
}
