
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace MCSM {
    using System;
    using Terminal.Gui;
    
    
    public partial class ModManage : Terminal.Gui.View {
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.ListView listView;
        
        private Terminal.Gui.ListView listView2;
        
        private void InitializeComponent() {
            this.listView2 = new Terminal.Gui.ListView();
            this.listView = new Terminal.Gui.ListView();
            this.label2 = new Terminal.Gui.Label();
            this.label = new Terminal.Gui.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.label.Width = Dim.Percent(50);
            this.label.Height = 1;
            this.label.X = 1;
            this.label.Y = 0;
            this.label.Visible = true;
            this.label.Data = "label";
            this.label.Text = "ENABLED";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label);
            this.label2.Width = Dim.Percent(50);
            this.label2.Height = 1;
            this.label2.X = Pos.Percent(50);
            this.label2.Y = 0;
            this.label2.Visible = true;
            this.label2.Data = "label2";
            this.label2.Text = "DISABLED";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.listView.Width = Dim.Percent(50);
            this.listView.Height = Dim.Fill();
            this.listView.X = 1;
            this.listView.Y = 1;
            this.listView.Visible = true;
            this.listView.Data = "listView";
            this.listView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.listView.AllowsMarking = false;
            this.listView.AllowsMultipleSelection = true;
            this.Add(this.listView);
            this.listView2.Width = Dim.Percent(50);
            this.listView2.Height = Dim.Fill();
            this.listView2.X = Pos.Percent(50);
            this.listView2.Y = 1;
            this.listView2.Visible = true;
            this.listView2.Data = "listView2";
            this.listView2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.listView2.AllowsMarking = false;
            this.listView2.AllowsMultipleSelection = true;
            this.Add(this.listView2);
        }
    }
}
