
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace MCSM {
    using Terminal.Gui;
    
    
    public partial class InputDialog {
        public InputDialog(int index,List<string> L) {
            InitializeComponent();
            textField.Text = L[index];
            this.ButtonAlignment = ButtonAlignments.Justify;
            this.button.Clicked += () =>{
                this.RequestStop();
            };
            this.button2.Clicked += () => {
                L[index] = textField.Text.ToString();
                this.RequestStop();
            };
        }
    }
}
