
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace MCSM {
    using System;
    using Terminal.Gui;
    
    
    public partial class WaitDialog : Terminal.Gui.Dialog {
        
        private Terminal.Gui.Label label;
        private void InitializeComponent() {
            this.ColorScheme = MainProc.DispStyle;
            this.label = new Terminal.Gui.Label();
            this.Width = 20;
            this.Height = 5;
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Modal = true;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = true;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.label.Width = 4;
            this.label.Height = 1;
            this.label.X = Pos.Center();
            this.label.Y = Pos.Center();
            this.label.Visible = true;
            this.label.Data = "label";
            this.label.Text = "Please Wait ...";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label);
        }
    }
}
