
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace MCSM {
    using System;
    using Terminal.Gui;
    
    
    public partial class ItemDataBase : Terminal.Gui.Dialog {
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.RadioGroup radioGroup;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.RadioGroup radioGroup2;
        
        private Terminal.Gui.TextField textField;
        
        private Terminal.Gui.ListView listView;
        
        private Terminal.Gui.Button button;
        
        private Terminal.Gui.Button button2;
        
        private void InitializeComponent() {
            this.ColorScheme = MainProc.DispStyle;
            this.button2 = new Terminal.Gui.Button();
            this.button = new Terminal.Gui.Button();
            this.listView = new Terminal.Gui.ListView();
            this.textField = new Terminal.Gui.TextField();
            this.radioGroup2 = new Terminal.Gui.RadioGroup();
            this.label2 = new Terminal.Gui.Label();
            this.radioGroup = new Terminal.Gui.RadioGroup();
            this.label = new Terminal.Gui.Label();
            this.Width = Dim.Percent(85f);
            this.Height = Dim.Percent(85f);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Modal = true;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = true;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.label.Width = 4;
            this.label.Height = 1;
            this.label.X = 8;
            this.label.Y = 0;
            this.label.Visible = true;
            this.label.Data = "label";
            this.label.Text = "Type:";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label);
            this.radioGroup.Width = 24;
            this.radioGroup.Height = 1;
            this.radioGroup.X = 14;
            this.radioGroup.Y = 0;
            this.radioGroup.Visible = true;
            this.radioGroup.Data = "radioGroup";
            this.radioGroup.Text = "";
            this.radioGroup.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.radioGroup.RadioLabels = new NStack.ustring[] {
                    "Item",
                    "Block",
                    "Fluid"};
            this.radioGroup.DisplayMode = Terminal.Gui.DisplayModeLayout.Horizontal;
            this.Add(this.radioGroup);
            this.label2.Width = 4;
            this.label2.Height = 1;
            this.label2.X = 1;
            this.label2.Y = 1;
            this.label2.Visible = true;
            this.label2.Data = "label2";
            this.label2.Text = "Search with:";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.radioGroup2.Width = 30;
            this.radioGroup2.Height = 1;
            this.radioGroup2.X = 14;
            this.radioGroup2.Y = 1;
            this.radioGroup2.Visible = true;
            this.radioGroup2.Data = "radioGroup2";
            this.radioGroup2.Text = "";
            this.radioGroup2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.radioGroup2.RadioLabels = new NStack.ustring[] {
                    "English",
                    "chinese",
                    "pinyin"};
            this.radioGroup2.DisplayMode = Terminal.Gui.DisplayModeLayout.Horizontal;
            this.Add(this.radioGroup2);
            this.textField.Width = Dim.Fill();
            this.textField.Height = 1;
            this.textField.X = 1;
            this.textField.Y = 2;
            this.textField.Visible = true;
            this.textField.Secret = false;
            this.textField.Data = "textField";
            this.textField.Text = "";
            this.textField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textField);
            this.listView.Width = Dim.Fill();
            this.listView.Height = Dim.Fill();
            this.listView.X = 1;
            this.listView.Y = 3;
            this.listView.Visible = true;
            this.listView.Data = "listView";
            this.listView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.listView.AllowsMarking = false;
            this.listView.AllowsMultipleSelection = true;
            this.Add(this.listView);
            this.button.Width = 8;
            this.button.Height = 1;
            this.button.Visible = true;
            this.button.Data = "button";
            this.button.Text = "CANCEL";
            this.button.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button.IsDefault = false;
            this.AddButton(this.button);
            this.button2.Width = 8;
            this.button2.Height = 1;
            this.button2.Visible = true;
            this.button2.Data = "button2";
            this.button2.Text = "OK";
            this.button2.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button2.IsDefault = false;
            this.AddButton(this.button2);
        }
    }
}
