
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace MCSM {
    using System;
    using Terminal.Gui;
    
    
    public partial class ServerPropertiesEditor : Terminal.Gui.View {
        
        private Terminal.Gui.ListView listView;
        
        private Terminal.Gui.Button button;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.Button button2;
        
        private void InitializeComponent() {
            this.button2 = new Terminal.Gui.Button();
            this.label = new Terminal.Gui.Label();
            this.button = new Terminal.Gui.Button();
            this.listView = new Terminal.Gui.ListView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.listView.Width = Dim.Fill();
            this.listView.Height = Dim.Fill() - 1;
            this.listView.X = 1;
            this.listView.Y = 0;
            this.listView.Visible = true;
            this.listView.Data = "listView";
            this.listView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.listView.Source = null;
            this.listView.AllowsMarking = false;
            this.listView.AllowsMultipleSelection = true;
            this.Add(this.listView);
            this.button.Width = 9;
            this.button.Height = 1;
            this.button.X = 1;
            this.button.Y = Pos.AnchorEnd()-1;
            this.button.Visible = true;
            this.button.Data = "button";
            this.button.Text = "SAVE";
            this.button.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button.IsDefault = false;
            this.Add(this.button);
            this.label.Width = 20;
            this.label.Height = 1;
            this.label.X = 9;
            this.label.Y = Pos.AnchorEnd()-1;
            this.label.Visible = true;
            this.label.Data = "label";
            this.label.Text = "";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label);
            this.button2.Width = 10;
            this.button2.Height = 1;
            this.button2.X = Pos.AnchorEnd() - 11;
            this.button2.Y = Pos.AnchorEnd()-1;
            this.button2.Visible = true;
            this.button2.Data = "button2";
            this.button2.Text = "RELOAD";
            this.button2.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.button2.IsDefault = false;
            this.Add(this.button2);
        }
    }
}
